//协议处理基础功能

#pragma once

//#define PROTOCOL_CODE_DLT645_1997 "DLT645_1997"
//#define PROTOCOL_CODE_DLT645_2007 "DLT645_2007"
#define PROTOCOL_CODE_MODBUS_TCP "MODBUS_TCP"
#define PROTOCOL_CODE_MODBUS_RTU_TCP "MODBUS_RTU_TCP"
#define PROTOCOL_CODE_MODBUS_RTU "MODBUS_RTU"
#define PROTOCOL_CODE_TCP_TUNNEL "TCP_TUNNEL"
#define PROTOCOL_CODE_SERIAL_PORT_TUNNEL "SERIAL_PORT_TUNNEL"
#define PROTOCOL_CODE_TCP_DEMO "TCP_DEMO"
#define PROTOCOL_CODE_SERIAL_PORT_DEMO "SERIAL_PORT_DEMO"
